version: '3.8'

services:
  web:
    build: .
    ports:
      - "8004:8004"
    volumes:
      - pomodoro_data:/app/data

    restart: unless-stopped
    environment:
      - UV_PROJECT_ENVIRONMENT=/app/.venv

volumes:
  pomodoro_data: {}